server:
  port: 8080

spring:
  datasource:
    dynamic:
      #设置主库的名称为
      primary: master # 默认
      datasource:
        #        主库，最好为master，用于上边配置主库名称
        master:
          url: jdbc:mysql://127.0.0.1:3306/master?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: mysql123
          driver-class-name: com.mysql.cj.jdbc.Driver
          #从库，名字随意
        slave:
          url: jdbc:mysql://127.0.0.1:3306/slave?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: mysql123
          driver-class-name: com.mysql.cj.jdbc.Driver
##mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/zhaolearn/many_datasource/business/*Mapper.xml
    #  configuration:
  #     这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


