server:
  port: 8079
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql123
    #使用com.mysql.jdbc.Driver也行，但是会报WARN
    driver-class-name: com.mysql.cj.jdbc.Driver